const te=new TextEncoder(),td=new TextDecoder();
let CRC_TABLE=null;
function crcTable(){if(CRC_TABLE)return CRC_TABLE;CRC_TABLE=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;CRC_TABLE[n]=c>>>0;}return CRC_TABLE;}
export function crc32(bytes){const t=crcTable();let c=0xffffffff;for(const b of bytes)c=t[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function dosDateTime(d){d=d||new Date();let y=Math.max(1980,d.getFullYear());return{time:((d.getHours()&31)<<11)|((d.getMinutes()&63)<<5)|((Math.floor(d.getSeconds()/2))&31),date:(((y-1980)&127)<<9)|(((d.getMonth()+1)&15)<<5)|(d.getDate()&31)};}
function concat(parts,total){const out=new Uint8Array(total??parts.reduce((n,p)=>n+p.length,0));let o=0;for(const p of parts){out.set(p,o);o+=p.length;}return out;}
function localHeader(name,data,crc,dt){const nb=te.encode(name),h=new Uint8Array(30+nb.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x0800,true);v.setUint16(8,0,true);v.setUint16(10,dt.time,true);v.setUint16(12,dt.date,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,nb.length,true);v.setUint16(28,0,true);h.set(nb,30);return h;}
function centralHeader(name,data,crc,dt,offset){const nb=te.encode(name),h=new Uint8Array(46+nb.length),v=new DataView(h.buffer);v.setUint32(0,0x02014b50,true);v.setUint16(4,20,true);v.setUint16(6,20,true);v.setUint16(8,0x0800,true);v.setUint16(10,0,true);v.setUint16(12,dt.time,true);v.setUint16(14,dt.date,true);v.setUint32(16,crc,true);v.setUint32(20,data.length,true);v.setUint32(24,data.length,true);v.setUint16(28,nb.length,true);v.setUint16(30,0,true);v.setUint16(32,0,true);v.setUint16(34,0,true);v.setUint16(36,0,true);v.setUint32(38,0,true);v.setUint32(42,offset,true);h.set(nb,46);return h;}
export function createStoreZip(entries){if(entries.length>65535)throw new Error('ZIP entry limit exceeded');const local=[],central=[];let offset=0,localSize=0,centralSize=0;for(const e of entries){const data=e.data instanceof Uint8Array?e.data:new Uint8Array(e.data),crc=crc32(data),dt=dosDateTime(e.mtime);const lh=localHeader(e.name,data,crc,dt),ch=centralHeader(e.name,data,crc,dt,offset);local.push(lh,data);central.push(ch);offset+=lh.length+data.length;localSize+=lh.length+data.length;centralSize+=ch.length;}const end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(4,0,true);v.setUint16(6,0,true);v.setUint16(8,entries.length,true);v.setUint16(10,entries.length,true);v.setUint32(12,centralSize,true);v.setUint32(16,localSize,true);v.setUint16(20,0,true);return concat([...local,...central,end],localSize+centralSize+22);}
export function parseStoreZip(buffer){const b=buffer instanceof Uint8Array?buffer:new Uint8Array(buffer),v=new DataView(b.buffer,b.byteOffset,b.byteLength),out=[];let o=0;while(o+4<=b.length&&v.getUint32(o,true)===0x04034b50){if(o+30>b.length)throw new Error('Truncated ZIP header');const flags=v.getUint16(o+6,true),method=v.getUint16(o+8,true),crc=v.getUint32(o+14,true),size=v.getUint32(o+18,true),usize=v.getUint32(o+22,true),nl=v.getUint16(o+26,true),el=v.getUint16(o+28,true);if(method!==0)throw new Error('Only Bind Build uncompressed ZIP backups are supported');if(size!==usize)throw new Error('Unexpected compressed ZIP entry');const ns=o+30,ds=ns+nl+el,de=ds+size;if(de>b.length)throw new Error('Truncated ZIP file');const name=td.decode(b.subarray(ns,ns+nl)),data=b.slice(ds,de);if(crc32(data)!==crc)throw new Error('ZIP checksum failed for '+name);out.push({name,data,utf8:Boolean(flags&0x0800)});o=de;}if(!out.length)throw new Error('No files found in ZIP');return out;}
export function utf8Bytes(text){return te.encode(text);}
export function utf8Text(bytes){return td.decode(bytes);}
