import { supabase } from '../lib/supabase.js';import { mountShell } from '../lib/shell.js';import { toast,fail,esc,fmtDate } from '../lib/ui.js';
const $=(s,c=document)=>c.querySelector(s);const user=await mountShell({route:'backup',title:'Backup & Operations'});if(!user)throw new Error('redirecting');const can=['founder','admin'].includes(user.role);let PAYLOAD=null,VALID=null;
const bytes=n=>{n=Number(n)||0;if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB';};
async function load(){try{const [b,r,n]=await Promise.all([supabase.from('application_backup_log').select('*').order('created_at',{ascending:false}).limit(20),supabase.from('automation_runs').select('*').order('started_at',{ascending:false}).limit(12),supabase.from('erp_notifications').select('*').order('created_at',{ascending:false}).limit(20)]);[b,r,n].forEach(x=>{if(x.error)throw x.error;});paint(b.data||[],r.data||[],n.data||[]);}catch(e){fail(e);}}
function paint(backups,runs,alerts){const last=backups.find(x=>x.operation==='export'&&x.status==='success'),run=runs[0];$('#kAlerts').textContent=String(alerts.filter(x=>x.status==='unread').length);$('#kBackup').textContent=last?fmtDate(last.created_at):'None';$('#kRun').textContent=run?fmtDate(run.started_at):'None';$('#exportBackupBtn').disabled=!can;$('#runAutomationBtn').disabled=!can;
$('#backupBody').innerHTML=backups.length?backups.map(x=>'<tr><td>'+fmtDate(x.created_at)+'</td><td>'+esc(x.operation)+'</td><td>'+Number(x.row_count||0).toLocaleString('en-IN')+'</td><td>'+bytes(x.byte_estimate)+'</td><td><span class="sys-status '+esc(x.status)+'">'+esc(x.status)+'</span></td></tr>').join(''):'<tr><td colspan="5">No backup operations yet.</td></tr>';
$('#runList').innerHTML=runs.length?runs.map(x=>'<div class="sys-row"><div class="sys-row__body"><div class="sys-row__title">'+esc(x.job_name)+'</div><div class="sys-row__meta">'+fmtDate(x.started_at)+(x.result?.notifications_created!==undefined?' · '+x.result.notifications_created+' alerts created':'')+(x.error?' · '+esc(x.error):'')+'</div></div><span class="sys-status '+esc(x.status)+'">'+esc(x.status)+'</span></div>').join(''):'<div class="sys-row__meta">No automation runs recorded yet.</div>';
$('#alertList').innerHTML=alerts.length?alerts.slice(0,10).map(x=>'<div class="sys-row"><div class="sys-row__body"><div class="sys-row__title">'+esc(x.title)+'</div><div class="sys-row__meta">'+esc(x.body||'')+' · '+fmtDate(x.created_at)+'</div></div><span class="sys-status '+(x.severity==='critical'?'failed':x.status==='unread'?'blocked':'ok')+'">'+esc(x.severity)+'</span></div>').join(''):'<div class="sys-row__meta">No operational alerts.</div>';}
$('#exportBackupBtn').addEventListener('click',async()=>{if(!can)return;try{$('#exportBackupBtn').disabled=true;toast('Building ERP backup…');const {data,error}=await supabase.rpc('export_application_backup');if(error)throw error;const raw=JSON.stringify(data,null,2),url=URL.createObjectURL(new Blob([raw],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='bindbuild-erp-backup-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';a.click();URL.revokeObjectURL(url);toast('Backup downloaded · '+Number(data.row_count||0).toLocaleString('en-IN')+' rows');await load();}catch(e){fail(e);}finally{$('#exportBackupBtn').disabled=!can;}});
$('#backupFile').addEventListener('change',async e=>{PAYLOAD=null;VALID=null;$('#restoreBtn').disabled=true;const file=e.target.files?.[0];if(!file)return;try{PAYLOAD=JSON.parse(await file.text());const {data,error}=await supabase.rpc('validate_application_backup',{p_payload:PAYLOAD});if(error)throw error;VALID=data;$('#validationBox').innerHTML='<div class="sys-file">'+esc(file.name)+'</div><div class="sys-kv"><span>Format</span><b>v'+data.format_version+'</b></div><div class="sys-kv"><span>Tables</span><b>'+data.table_count+'</b></div><div class="sys-kv"><span>Rows</span><b>'+Number(data.row_count).toLocaleString('en-IN')+'</b></div><div class="sys-kv"><span>Restore target</span><b>'+(data.restore_allowed?'Empty / allowed':'Live data / blocked')+'</b></div><div class="sys-note '+(data.restore_allowed?'':'warn')+'">'+esc(data.note)+'</div>';$('#restoreBtn').disabled=!(can&&data.restore_allowed);toast('Backup validated');await load();}catch(err){PAYLOAD=null;VALID=null;$('#validationBox').innerHTML='<div class="sys-note warn">'+esc(err.message||String(err))+'</div>';fail(err);}});
$('#restoreBtn').addEventListener('click',async()=>{if(!can||!PAYLOAD||!VALID?.restore_allowed)return;const word=prompt('Type RESTORE to confirm importing this backup into the empty ERP');if(word!=='RESTORE')return toast('Restore cancelled','err');if(!confirm('Final confirmation: restore the validated backup?'))return;try{$('#restoreBtn').disabled=true;const {data,error}=await supabase.rpc('restore_application_backup',{p_payload:PAYLOAD});if(error)throw error;toast('Restore complete · '+Number(data.rows_inserted||0).toLocaleString('en-IN')+' rows');await load();}catch(e){fail(e);}finally{$('#restoreBtn').disabled=!(can&&VALID?.restore_allowed);}});
$('#runAutomationBtn').addEventListener('click',async()=>{if(!can)return;try{$('#runAutomationBtn').disabled=true;const {data,error}=await supabase.rpc('run_erp_automations_now');if(error)throw error;toast('Automation scan complete · '+Number(data.notifications_created||0)+' new alerts');await load();}catch(e){fail(e);}finally{$('#runAutomationBtn').disabled=!can;}});
await load();